/* File storage behind an interface (CLAUDE.md adapters). MinIO cannot be pulled on this machine (HANDOVER gap 2), so dev
   and tests keep files in a local folder; an S3-compatible adapter (same interface) comes before staging. Keys are
   generated by the API (tenants/<tenant>/receipts/<id>/<copy>-<format>-<lang>.pdf), never taken from a request. */
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve, sep } from "node:path";

export interface Storage {
  readonly name: string;
  /** Writes once: an existing key is never overwritten (stored documents are immutable). */
  put(key: string, bytes: Uint8Array, contentType: string): Promise<void>;
  get(key: string): Promise<Uint8Array | null>;
}

const KEY = /^[A-Za-z0-9_-]+(\/[A-Za-z0-9_.-]+)*$/;

export class LocalFolderStorage implements Storage {
  readonly name = "local-folder";
  constructor(private root: string) {}
  private path(key: string): string {
    if (!KEY.test(key) || key.includes("..")) throw new Error(`storage: invalid key ${key}`);
    const p = resolve(this.root, ...key.split("/"));
    if (!p.startsWith(resolve(this.root) + sep)) throw new Error(`storage: key escapes the root: ${key}`);
    return p;
  }
  async put(key: string, bytes: Uint8Array): Promise<void> {
    const p = this.path(key);
    await mkdir(dirname(p), { recursive: true });
    try { await writeFile(p, bytes, { flag: "wx" }); }
    catch (e) { if ((e as { code?: string }).code === "EEXIST") throw new Error(`storage: ${key} already exists`); throw e; }
  }
  async get(key: string): Promise<Uint8Array | null> {
    try { return await readFile(this.path(key)); } catch (e) { if ((e as { code?: string }).code === "ENOENT") return null; throw e; }
  }
}

/** STORAGE_DIR (.env) or <repo>/var/storage (gitignored). */
export const storage: Storage = new LocalFolderStorage(process.env.STORAGE_DIR ?? resolve(process.cwd().replace(/[\\/]apps[\\/]api$/, ""), "var", "storage"));
