/* File storage behind an interface (CLAUDE.md adapters). Dev and tests keep files in a local folder; staging and
   production use S3Storage (any S3-compatible store: AWS S3, Cloudflare R2, MinIO) — STORAGE=s3. Keys are generated by
   the API (tenants/<tenant>/receipts/<id>/<copy>-<format>-<lang>.pdf), never taken from a request. The bucket is
   private and the API streams every file itself after its own permission check and audit (Kamrul 08/10/2026: no signed
   URLs to clients — a signed URL would bypass both). Signing is SigV4 by aws4fetch (72 KB; ADR 0019). */
import { AwsClient } from "aws4fetch";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve, sep } from "node:path";

export interface Storage {
  readonly name: string;
  /** Writes once: an existing key is never overwritten (stored documents are immutable). */
  put(key: string, bytes: Uint8Array, contentType: string): Promise<void>;
  get(key: string): Promise<Uint8Array | null>;
}

const KEY = /^[A-Za-z0-9_-]+(\/[A-Za-z0-9_.-]+)*$/;

export class LocalFolderStorage implements Storage {
  readonly name = "local-folder";
  constructor(private root: string) {}
  private path(key: string): string {
    if (!KEY.test(key) || key.includes("..")) throw new Error(`storage: invalid key ${key}`);
    const p = resolve(this.root, ...key.split("/"));
    if (!p.startsWith(resolve(this.root) + sep)) throw new Error(`storage: key escapes the root: ${key}`);
    return p;
  }
  async put(key: string, bytes: Uint8Array): Promise<void> {
    const p = this.path(key);
    await mkdir(dirname(p), { recursive: true });
    try { await writeFile(p, bytes, { flag: "wx" }); }
    catch (e) { if ((e as { code?: string }).code === "EEXIST") throw new Error(`storage: ${key} already exists`); throw e; }
  }
  async get(key: string): Promise<Uint8Array | null> {
    try { return await readFile(this.path(key)); } catch (e) { if ((e as { code?: string }).code === "ENOENT") return null; throw e; }
  }
}

export interface S3Config { endpoint: string; region: string; bucket: string; accessKeyId: string; secretAccessKey: string; pathStyle: boolean }
export class S3Storage implements Storage {
  readonly name = "s3";
  private aws: AwsClient;
  constructor(private c: S3Config) { this.aws = new AwsClient({ accessKeyId: c.accessKeyId, secretAccessKey: c.secretAccessKey, service: "s3", region: c.region }); }
  private url(key: string): string {
    if (!KEY.test(key) || key.includes("..")) throw new Error(`storage: invalid key ${key}`);
    const base = this.c.endpoint.replace(/\/+$/, "");
    if (this.c.pathStyle) return `${base}/${this.c.bucket}/${key}`;
    const u = new URL(base); u.hostname = `${this.c.bucket}.${u.hostname}`;
    return `${u.origin}/${key}`;
  }
  /** Written once: If-None-Match: * makes the store refuse a second write of the same key (412). */
  async put(key: string, bytes: Uint8Array, contentType: string): Promise<void> {
    const r = await this.aws.fetch(this.url(key), { method: "PUT", body: bytes as unknown as BodyInit, headers: { "content-type": contentType, "if-none-match": "*" } });
    if (r.status === 412) throw new Error(`storage: ${key} already exists`);
    if (!r.ok) throw new Error(`storage: put ${key} failed (HTTP ${r.status})`);
  }
  async get(key: string): Promise<Uint8Array | null> {
    const r = await this.aws.fetch(this.url(key), { method: "GET" });
    if (r.status === 404) return null;
    if (!r.ok) throw new Error(`storage: get ${key} failed (HTTP ${r.status})`);
    return new Uint8Array(await r.arrayBuffer());
  }
}

/** STORAGE=s3 (S3_ENDPOINT, S3_REGION, S3_BUCKET, S3_ACCESS_KEY, S3_SECRET_KEY, S3_PATH_STYLE=1 for MinIO), else a local
    folder: STORAGE_DIR or <repo>/var/storage (gitignored). Production refuses the local folder (config.ts). */
export function storageFromEnv(env: NodeJS.ProcessEnv = process.env): Storage {
  if (env.STORAGE === "s3") {
    const need = ["S3_ENDPOINT", "S3_BUCKET", "S3_ACCESS_KEY", "S3_SECRET_KEY"].filter((k) => !env[k]);
    if (need.length) throw new Error(`STORAGE=s3 needs ${need.join(", ")}`);
    return new S3Storage({ endpoint: env.S3_ENDPOINT!, region: env.S3_REGION || "auto", bucket: env.S3_BUCKET!, accessKeyId: env.S3_ACCESS_KEY!, secretAccessKey: env.S3_SECRET_KEY!, pathStyle: env.S3_PATH_STYLE === "1" });
  }
  return new LocalFolderStorage(env.STORAGE_DIR ?? resolve(process.cwd().replace(/[\\/]apps[\\/]api$/, ""), "var", "storage"));
}
export const storage: Storage = storageFromEnv();
